[package]
name = "hkv-server"
version = "0.1.0"
edition = "2024"

[dependencies]
hkv-engine = { path = "../hkv-engine" }
hkv-common = { path = "../hkv-common" }
bytes = "1"
tokio = { version = "1", features = ["full"] }
